### ISSUE TITLE
Sphinx doc: Duplicate class entries

### ISSUE THREAD

**Issue by tiltowait** [hynek/doc2dash#111]
I've generated a docset for Dash from [this repository's documentation](https://github.com/Pycord-Development/pycord), which uses Sphinx. While my docset works, I have two separate links to every class. For instance, if I type "member", I get a link for `discord` and a link to `discord.member`. Both links go to the same location, and it interrupts my workflow because I have to navigate though each nested list instead of just hitting enter once.

See the following example:

![Image ref](https://tilt-assets.s3-us-west-1.amazonaws.com/dash.png)

I am opening the issue here at the suggestion of Dash's developer.

**Comment by hynek** [comment]
From what I see that class is known to Sphinx in two namespaces so it seems correct to me to show it to you twice.

**Comment by tiltowait** [comment]
Drat! Guess I'll have to do some digging to find out how to disable that in Sphinx. Thanks for the reply.
