### ISSUE TITLE
[Request] Create Homebrew formula

### ISSUE THREAD

**Issue by xilopaint** [hynek/doc2dash#127]
Since v3 has a macOS stand-alone binary a Homebrew formula would be helpful for installation.

**Comment by hynek** [comment]
I would love to provide one (maybe that could even be used without the binaries), but I have no idea how and this release was an incredible ton of work as it stands and I didn't want to delay it any further.

**Comment by xilopaint** [comment]
> (maybe that could even be used without the binaries), but I have no idea how

I think the binary is a better choice than the former pip package but it can be even better if we can install it via Homebrew.

**Comment by hynek** [comment]
Agreed in general, but they _do_ add a certain amount of complexity / wonkiness and more importantly aren't available for all possible platforms (notably ARM). I'd rather try Homebrew's builtin support for Python apps first.

Would you mind installing and testing `brew install hynek/doc2dash/doc2dash` for me?

(I know it's very slow 10 minutes here – I'll look into bottles when I have time for this again. The whole topic is somewhat overwhelming.)

**Comment by xilopaint** [comment]
I don't understand why `brew install` takes so long. Can't you just create a formula to download the binary from GitHub releases?

**Comment by hynek** [comment]
Not until someone bestows a Apple silicon Mac on me.

I'm trying to go the _official_ way to package Python apps for Homebrew for now if just for the reason that it's plausible that other people / Homebrew would be opposed to binary blob-only kegs.

I've been able to build a bottle locally and trying to get it built it in CI now: https://github.com/hynek/homebrew-doc2dash/actions/runs/3052040702/jobs/4920976895

If I can make the work, it should accelerate the whole thing dramatically.

**Comment by hynek** [comment]
Please try again! 🤞

**Comment by hynek** [comment]
I'll look into submitting when I have the emotional energy to learn another bureaucracy. 😅 I think I'll source an M1 bottle from someone trustworthy for now.

**Comment by xilopaint** [comment]
Hey @hynek, I'm getting this output when running `brew doctor`:

```
Warning: Some installed formulae are not readable:
  doc2dash: /usr/local/Homebrew/Library/Taps/hynek/homebrew-doc2dash/Formula/doc2dash.rb:11: syntax error, unexpected <<, expecting end
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/hynek/homebrew-doc2dash/Formula/doc2dash.rb:20: syntax error, unexpected ===, expecting end
=======
^~~
/usr/local/Homebrew/Library/Taps/hynek/homebrew-doc2dash/Formula/doc2dash.rb:29: syntax error, unexpected >>, expecting end
>>>>>>> 0aeb154 (Add bottles)
^~
/usr/local/Homebrew/Library/Taps/hynek/homebrew-doc2dash/Formula/doc2dash.rb:79: syntax error, unexpected end, expecting end-of-input

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo hynek/doc2dash) checkout main
```

**Comment by xilopaint** [comment]
> Can you somehow start over?

haha it's a good time to do it as I just got a brand new Mac.

**Comment by xilopaint** [comment]
Btw, should it work on a M2 Mac?

**Comment by hynek** [comment]
Um, I would assume? It has an M1 bottle.
