### ISSUE TITLE
Built docset not following web-based width css parameters

### ISSUE THREAD

**Issue by j9ac9k** [hynek/doc2dash#134]
Hello!

I have been working on generating a docset for pyqtgraph, a project I maintain with some other folks, which currently uses the pydata-sphinx-theme.  I apologize for the large (and very wide) screenshots; I'm hoping they can highlight the issue.

In the built docset, the text does not expand to fill the available width of the dash window, and I'm not sure how to even go about debugging it.

![image](https://user-images.githubusercontent.com/646398/194939810-7142ee63-624f-420d-9502-d9e8789c773a.png)

But within dash, if I select "open local page" I get a browser where the contents do expand horizontally to fill the entire available space:

![image](https://user-images.githubusercontent.com/646398/194939950-c2fddf6b-038c-4a22-8173-c2d7bb8ebdd8.png)

I should note, there is precedence that within dash the docs can expand to fill the available horizontal space; note this page from the python3 docset:

![image](https://user-images.githubusercontent.com/646398/194940099-b244769e-cff4-451d-a3bf-c20e0e3cd395.png)

I'm not sure if this is a Dash issue, or a doc2dash issue.  Any input would be greatly appreciated.

**Comment by hynek** [comment]
Since doc2dash doesn't do anything to the design, let's ask @Kapeli

**Comment by Kapeli** [comment]
Dash doesn't add any CSS that should affect the width of the page.

You can enable Dash's web inspector by running this command in Terminal: `defaults write com.kapeli.dashdoc WebKitDeveloperExtras YES` and relaunch Dash, after which you should have an Inspect Element option when you right click.

**Comment by j9ac9k** [comment]
ok, this is weird, after setting `defaults write com.kapeli.dashdoc WebKitDeveloperExtras YES` and relaunching, content is now taking the entire width of the page

![image](https://user-images.githubusercontent.com/646398/195164867-ac2494e9-1df9-494b-8c06-6b90d25a883b.png)

I was using doc2dash with the following args:

```bash
	doc2dash -n pyqtgraph\
	 --online-redirect-url https://pyqtgraph.readthedocs.io/en/latest\
	 --icon source/_static/peegee_03_square_no_bg_32_cleaned.png\
	 --force\
	 -A\
	 build/html
```

Would there be caching issues involved here where dash would cache the css of a docset and not get overridden the next time I replaced it?

**Comment by Kapeli** [comment]
Yes. Relaunch Dash after making changes, or disable caching from the web inspector.

**Comment by j9ac9k** [comment]
While the command `defaults write com.kapeli.dashdoc WebKitDeveloperExtras YES` did not appear to unlock any kind of CSS inspect functionality; restarting dash (not just removing/re-importing the docset was not sufficient) was the trick...

https://www.youtube.com/watch?v=5UT8RkSmN4k
