### ISSUE TITLE
doc2dash rendered source output  is new-line separated

### ISSUE THREAD

**Issue by j9ac9k** [hynek/doc2dash#135]
Hello!

I'm not sure if this is a bug with dash, bug with doc2dash, or something silly I'm doing on my docset.

When viewing the source code-block, inside dash, there is newline separation on virtually every space outside of the docstring.  The HTML file that went into doc2dash renders the content correctly:

On the left is dash, on the right is my browser

<img width="1814" alt="image" src="https://user-images.githubusercontent.com/646398/199389552-ac78cca7-63cb-4fe6-8145-d769aa426f5d.png">

I did notice that for a brief moment, dash renders the content correctly, and then updates.  I captured a video screenshot of this.

https://user-images.githubusercontent.com/646398/199389813-2af48228-b8c8-4f42-875f-6dcef6d7b1e5.mov

As the HTML file that doc2dash imports looks fine, I'm not sure where I should look at for further debugging.

EDIT: I scrolled down in the doc window, after I get outside of the "highlighted" code section, the source code renders fine?

<img width="945" alt="image" src="https://user-images.githubusercontent.com/646398/199390530-e4e19e8d-6dc0-4381-88a6-271bf5bc5b0c.png">

**Comment by hynek** [comment]
You can always look into the docset and check the HTML by hand.

It's at: `XXX.docset/Contents/Resources/Documents/`

**Comment by j9ac9k** [comment]
got ot the bottom of it, closing this issue out.

When inspecting the page on a browser, I noticed that the CSS property `display: block` was specified by a user-agent.  When I added that attribute to my `dash.css` file, all looked well.  Closing out the issue, sorry for the noise, thanks for your input @hynek
