### ISSUE TITLE
Question: What the difference between `--add-to-dash / -a` vs `--add-to-global / -A`?

### ISSUE THREAD

**Issue by paw-lu** [hynek/doc2dash#137]
What the difference between `--add-to-dash / -a` vs `--add-to-global / -A`?

I see from `--help` that `--add-to-global / -A` adds to the default global directory for das2doc. So what does `--add-to-dash / -a` do? What would motivate me to use one over the other?

---

Love the library by the way, that a lot for sharing it. Makes Dash _so_ much more useful.

**Comment by hynek** [comment]
The difference is at what path it builds the docset before adding it to Dash.

`-A` puts it to `~/Library/Application Support/doc2dash/DocSets`. `-a` puts it into into the current directory or wherever `-d` points to.

**Comment by paw-lu** [comment]
Ah okay so where the actual `*.docset` directory lives? Thanks!
