### ISSUE TITLE
'Can't find anchor ... in ...' error when compiling docs with doc2dash

### ISSUE THREAD

**Issue by capac** [hynek/doc2dash#139]
When I build the _statsmodels_ docs for Dash, I usually get these types of errors, the `'Can't find anchor ... in ...'`. Below are some such examples. Even so, the docs are created, however what I've noticed is that some index entries are repeated, such as the entries for `sections` (see image below).

Is this a _statsmodels_ issue, or can it be confronted in _doc2dash_ ?

`Can't find anchor 'statsmodels.genmod.families.links.CLogLog' (EntryType.CLASS) in 'generated/statsmodels.genmod.families.links.CLogLog.html'.`

`Can't find anchor 'statsmodels.genmod.families.links.Log' (EntryType.SECTION) in 'generated/statsmodels.genmod.families.links.Log.html'.`

`Can't find anchor 'statsmodels.genmod.families.links.CLogLog.deriv' (EntryType.METHOD) in 'generated/statsmodels.genmod.families.links.CLogLog.deriv.html'.`

<img width="1035" alt="repeated-entries-in-sections" src="https://user-images.githubusercontent.com/541813/205020019-9b434e5e-311b-49e8-b09c-0e69fc1ce055.png">

**Comment by capac** [comment]
It appears that _statsmodels_ takes into account case-sensitive links for case-sensitive file systems. However in my case the file system turns out to be case-insensitive. Is there a way in _doc2dash_ to tell the parser (or another feature for that matter) to skip the redundant links for case-insensitive file systems?

**Comment by hynek** [comment]
Firstly: doc2dash will create the docset just fine if it can't patch the anchors – that's a bit of a separate feature.

---

I'm currently trying to build the docs locally but it feels like it's trying to mine a bitcoin or something. I've never seen a docs build process so slow.

Then I suppose we talk about this: <https://www.statsmodels.org/devel/generated/statsmodels.genmod.families.links.CLogLog.deriv.html>?

It looks like `sphinx_material` uses different markup for signatures. Would you mind locally locating this block:

https://github.com/hynek/doc2dash/blob/46bba9b667da609bb38981901dde1e68574d925f/src/doc2dash/parsers/intersphinx.py#L170-L181

And adding:

```python
or soup.find("dt", {"class": "sig"}, id=anchor)
```

in there? The farther up the faster. If it doesn't help, maybe try playing with it a bit.

My docs build is still ongoing with a ton of errors including SSL validation problems, so I'm not sure it will even work.

Worst case, could you attach your built docs?

**Comment by capac** [comment]
Using your patch, I got 45 anchor error messages during build. Now my docs build is just above 500 MB, instead of 660 MB before using the patch. However, the duplicate entries in the documents sections are still there, unfortunately. Starting from version 0.14, the statsmodels docs should remove the case-sensitive links. When I have time, I'll compile the docs on that branch.

**Comment by hynek** [comment]
Any news?

**Comment by capac** [comment]
Still no news to report on. I'm still waiting for version 0.14 of Statsmodels.
