### ISSUE TITLE
Allow GitHub paths for docset generation.

### ISSUE THREAD

**Issue by spott** [hynek/doc2dash#171]
Instead of requiring the workflow of cloning repo, building docs, then doing doc2dash, instead allow for the workflow of pointing at a GitHub repo and having doc2dash clone, build and do the doc conversion all at once.

Other options involve pointing at GitHub pages for documentation (so the build doesn't need to happen), or doing a pip install and build docs from that.  But some process that allows the input to not be a local copy of the source for the documentation would be ideal.

I realize that there is likely a number of edge cases in building documentation that might make this hard/impossible in the general case, but I think it might be doable for something like general python documentation that uses sphynx, or that has a GitHub pages site without too much effort (though I could be very wrong here).

**Comment by hynek** [comment]
What you're asking for here, complexity-wise, an entirely new application that, as a final step, invokes _doc2dash_ after handling a ton of jank. I mean, it would be **great**, if sOmEoNe built that, but _I_ don't have the bandwidth for it.
