### ISSUE TITLE
Mathjax doesn't display

### ISSUE THREAD

**Issue by edubkendo** [hynek/doc2dash#21]
I'm not sure if this is a Dash problem or a doc2dash problem, but I was generating a docset from [Julia's docs](http://julialang.org) and the beautifully rendered math in the documentation (for instance take a look at http://docs.julialang.org/en/latest/stdlib/linalg/ ). If I have Dash open the file in the browser, it seems to display correctly, but inside Dash itself, I see:
`\[Q = \prod_{i=1}^{\min(m,n)} (I - \tau_i v_i v_i^T)\]` instead of the math we see on the online docs.  I thought maybe the problem was the CDN it was using, so I carefully replaced that with a local copy of the javascript file, making sure the sphinx extension copied the correct path into the html.  Again, works in the browser but not in Dash.

A second, smaller issue, and perhaps one I should file separately, but even if I pass `--file-index index.html` it continues to use `genindex.html` as the index page.
cc @Kapeli

**Comment by xiumingzhang** [comment]
For the sake of future readers, include the `-j` flag in `doc2dash`, you will have 
```
<key>isJavaScriptEnabled</key>
<true/>
``` 
in the docset's `Info.plist`.

**Comment by hynek** [comment]
We should add it to the docs!
