### ISSUE TITLE
[request] Add ability to pass in a URL

### ISSUE THREAD

**Issue by econchick** [hynek/doc2dash#34]
I'm lazy, I don't want to clone a repo just to get their docs (I'm looking at you, Zope...) so I can build to Dash.  I'd love to be able to pass in the base/home URL of documentation to doc2dash, e.g.

```
doc2dash [OPTIONS] http://docs.zope.org/zope.interface/
```

**Comment by hynek** [comment]
People asked for this before but it is unfortunately impossible.  doc2dash needs the raw build otherwise stuff like #20 happens. :(   I really wish there’d be a better way…
