### ISSUE TITLE
Cannot import BeautifulSoup documentation

### ISSUE THREAD

**Issue by ptbrowne** [hynek/doc2dash#36]
Doc2Dash seems very cool but unfortunately, I was not able to import BeautifulSoup documentation :S

Steps to reproduce:

```
wget http://www.crummy.com/software/BeautifulSoup/bs4/download/4.3/beautifulsoup4-4.3.2.tar.gz
tar xzvf beautifulsoup4-4.3.2.tar.gz
cd beautifulsoup4-4.3.2/doc
make html
doc2dash -A build/html -n BeautifulSoup
```

In Dash, I see "Empty docset". When I open `beautifulsoup4-4.3.2/doc/build/html/index.html`, the documentation is good. Have I done something wrong ?

Thanks !

**Comment by hynek** [comment]
Is it possible that the documentation doesn’t use proper indices/API doc markup?

**Comment by ptbrowne** [comment]
Mmh I don't know. How can I know if it uses proper indices/API doc markup ?

**Comment by hynek** [comment]
Ideally there’s a file called `objects.inv` with something in it?

**Comment by ptbrowne** [comment]
```
$  find . | grep objects
./build/html/objects.inv

$ cat ./build/html/objects.inv
# Sphinx inventory version 2
# Project: Beautiful Soup
# Version: 4
# The remainder of this file is compressed using zlib.
xڕ�Mo
     �v���[�S�
              �z
t(�h��.�n/R7�yTV��S�}Qs"��E�4�'z>��.����5�p8�Hc�ݟ��@�>,VfRݐ�SD�EXkUI�AW�
                                                                         :�]+z�[G�←��┬'C�R3z$�����:���3�ʑ�26�2��>Z2G����T����HD0�RJEV�,-��W�X����pW����~A�G%xg<vт�xC�Y��^}��<qHK��
a����·≤:��<   �⎽Y]��π[�)��%⎼^�
                                                 4�GԻ[63׹�9�2]▮;°☃⎽▒  /⎻⎼☃┴▒├e/├└⎻/be▒┤├☃°┤┌⎽⎺┤⎻4↑4↓3↓2/d⎺c⏎
```

**Comment by hynek** [comment]
Before we start poking at that: is there also a genindex.html or genindex-all.html?

**Comment by ptbrowne** [comment]
The genindex.html is there but it is empty. See:



Le jeu. 30 avr. 2015 à 11:32, Hynek Schlawack <notifications@github.com> a
écrit :

**Comment by hynek** [comment]
That means that the bs4 docs are faulty. Doc2dash needs an API index to parse. All you can do is to try to ask the bs4 folks to fix their docs…
