### ISSUE TITLE
Not adding table of contents metadata with latest pydoctor

### ISSUE THREAD

**Issue by Kapeli** [hynek/doc2dash#38]
doc2dash isn't adding the table of contents metadata with docs that are generated using the latest pydoctor. Happens with the Twisted docs. No errors are shown.

**Comment by hynek** [comment]
Are you sure it’s a matter of the latest pydoctor or is it due to some changes to the docs layout? (i.e. does the problem occur if you generate old docs with new pydoctor and vice versa?)

In any case it seems like pydoctor is able to create `object.inv`s now if I’ll find time I may look into that too.

**Comment by Kapeli** [comment]
With the latest Twisted source:

* Generate docs using old(er) pydoctor then generate docset using doc2dash => table of contents works
* Generate docs using latest pydoctor => table of contents doesn't work

The layout of the docs definitely changed with the latest pydoctor. They use a new default theme now. Compare http://twistedmatrix.com/documents/13.2.0/api/ to http://twistedmatrix.com/documents/current/api/

**Comment by hynek** [comment]
Yeah I know, that’s why I asked whether it’s a layout thing or a pydoctor thing.  But sounds like pydoctor.

**Comment by Kapeli** [comment]
No idea to be honest. As far as I understand things, the layout is made by pydoctor.

**Comment by hynek** [comment]
cc @hawkowl

**Comment by hawkowl** [comment]
Yeah, pydoctor def. did change the layout, since pydoctor had things lying about that were from the change to t.w.template. I'll have a look.

**Comment by hawkowl** [comment]
The pydoctor header has changed again, to point to GitHub -- would that maybe cause it?

**Comment by hynek** [comment]
that might be although it should fail altogether then?  maybe it accidentally identifies it as intersphinx and something doesn’t quite work as it should?

If someone wants to dig please go for it; I’m traveling over Pentecost. 🍰

**Comment by hynek** [comment]
Fixed in #39 I believe,
