### ISSUE TITLE
Generated doc page is not completed

### ISSUE THREAD

**Issue by yangj1e** [hynek/doc2dash#40]
Hi, I tried to use `doc2dash` to generate documentation for `scikit-learn`, but I found that the `modules/classes.html` page is not completed.

This is what the page looks like in dash:

![screen shot 2015-06-16 at 2 14 55 pm](https://cloud.githubusercontent.com/assets/958760/8175945/1b53b270-1432-11e5-9ee6-b0b38df81270.png)

This is the original page:

![screen shot 2015-06-16 at 2 18 30 pm](https://cloud.githubusercontent.com/assets/958760/8175977/9ea41688-1432-11e5-9f37-8ee10b557f1d.png)

**Comment by hynek** [comment]
Could you provide me with an archive of the documentation you are trying to convert please?

**Comment by yangj1e** [comment]
https://drive.google.com/file/d/0B1jLoa9G1ngQZU0tWEtGU0hVRlk/view?usp=sharing

**Comment by hynek** [comment]
Hm works for me.  I have successfully created the following docket using the doc2dash that’s currently on PyPI: http://d.pr/f/1aRQV

Does it display okay in your dash.app?  Are you getting any errors when creating a docset?

**Comment by yangj1e** [comment]
Thank you. I just realized that maybe it's because I installed doc2dash in anaconda environment previously. So I just switched to use system python and it works well now.

**Comment by hynek** [comment]
Glad to hear!
