### ISSUE TITLE
Problem with table of content

### ISSUE THREAD

**Issue by yangj1e** [hynek/doc2dash#44]
I generated docset for scikit-learn but have trouble with the table of content.

In `API Reference`, clicking `sklearn.metrics` at the bottom left directs the page to the top instead of the anchor. So do `sklearn.metrics.cluster` and `sklearn.metrics.pairwise`.

The documentation I converted is https://drive.google.com/file/d/0B1jLoa9G1ngQWDBUSktWYV9JMVE/view?usp=sharing

**Comment by hynek** [comment]
What makes you think this is an bug in doc2dash?

**Comment by yangj1e** [comment]
Sorry I do not mean it is a bug in doc2dash. I just want to figure out how to solve the problem.

**Comment by yangj1e** [comment]
From the generated docset I found that the anchors of `sklearn.metrics` et al. were added above the API Reference header.
```
<div class="content">
<div class="documentwrapper">
<div class="bodywrapper">
<div class="body" role="main">
<div class="section" id="api-reference"><a name="//apple_ref/cpp/Module/sklearn.metrics.cluster"></a><a name="//apple_ref/cpp/Module/sklearn.metrics"></a><a name="//apple_ref/cpp/Module/sklearn.metrics.pairwise"></a><a name="//apple_ref/cpp/Module/sklearn.metrics.cluster"></a><a name="//apple_ref/cpp/Module/sklearn.metrics"></a><a name="//apple_ref/cpp/Module/sklearn.metrics.pairwise"></a>
<h1>API Reference<a class="headerlink" href="#api-reference" title="Permalink to this headline">¶</a></h1>
```
