### ISSUE TITLE
Problematic strict dependency version set

### ISSUE THREAD

**Issue by megies** [hynek/doc2dash#48]
Are all of those strict fixed dependency versions really necessary? This very particular set of version numbers makes it close to impossible to use `doc2dash` in an Anaconda environment..

**Comment by hynek** [comment]
Yes they are, doc2dash is an application that is tested against a set of dependencies that are known to work.

What exactly is so special about Anaconda that makes it close to impossible?  The 2.1.0 release with updated dependencies is overdue but it will be still pinned dependencies.

**Comment by megies** [comment]
Hmm.. actually I removed the `anaconda` package which has a crazy set of 180 fixed version dependencies and I guess that solves the problem. The name kind of suggested to me it's a vital package but everything seems to work without it as well.. no idea what it's function is. Anyway, thanks for the reply.

**Comment by hynek** [comment]
It still seems like you‘re having some misleading assumptions.  You should should always install applications into `virtualenv`s in any case.

**Comment by megies** [comment]
Well, I do.. but usually those stem from a clone from `root` (or a clone from a clone from root, etc., which also drags this `anaconda` package along. But, it now looks to me as if this `anaconda` package was a kind of a virtual package to set some coordinated fixed set of package versions. So basically one has to get rid of it to be more flexible with all the packages' versions.
