### ISSUE TITLE
tip: installing doc2dash on ElCapitan

### ISSUE THREAD

**Issue by pacav69** [hynek/doc2dash#50]
When installing doc2dash using pip on ElCapitan MAC OS it does not allow uninstalling six v 1.4.1 as it is a protected file.

Use the following to install doc2dash by ignoring six
$ sudo -H pip install doc2dash --ignore-installed six

For more information refer to https://github.com/pypa/pip/issues/3165 as it is a related issue.

Or

Use brew to install python then you can use pip without the problems of protected files.

**Comment by hynek** [comment]
I need to release 2.1 which has a big warning to never ever install doc2dash into global site-packages: http://doc2dash.readthedocs.org/en/latest/installation.html  :)
