### ISSUE TITLE
no option to overwrite existing docsets

### ISSUE THREAD

**Issue by ssbarnea** [hynek/doc2dash#51]
It seems that docs2dash fails if there is an already existing target dash file. We either need to be able to overwrite it by default or have an option for it. 

Removing the file before running docs2dash is not a viable option because the build may fail for other reasons.

    doc2dash --name jira docs/build/html --destination docs/build/docset --icon docs/_static/python-256.png --online-redirect-url https://jira.readthedocs.io/en/stable/
    Destination path "docs/build/docset/jira.docset" already exists.
    make: *** [docs] Error 17

**Comment by hynek** [comment]
Does http://doc2dash.readthedocs.io/en/stable/usage.html#cmdoption-f not do what you want?

**Comment by ssbarnea** [comment]
Oops, that's was clearly a RTFM. Sorry, maybe I do need glasses.
