### ISSUE TITLE
Crash when generating docset ("Couldn't find a tree builder with the features you requested: lxml")

### ISSUE THREAD

**Issue by rlow0** [hynek/doc2dash#52]
**Short version**
doc2dash crashes with an exception when I try to generate a docset. The problem appears to be caused by lxml 3.44 not playing well with beautifulsoup 4.4.1. No more trouble after updating lxml to version 3.6.0.

**Setup**
* doc2dash 2.1.0, installed with pip
* pip also installed the following libraries, which PyPI lists as dependencies:
    * zope.interface 4.1.3
    * six 1.10.0
    * lxml 3.4.4
    * colorama 0.3.7
    * click 6.3
    * beautifulsoup4 4.4.1
    * attrs 15.2.0
    * Sphinx 1.3.5
* Running python 3.5.1 (Anaconda 4.0.0)
* Mac OS X 10.10.4
* Trying to generate a docset for SymPy 1.0.

**Crash behavior**
Running the doc2dash command line utility. The error happens when calling `BeautifulSoup()` in `doc2dash.parsers.utils.py` (line 124). BeautifulSoup raises a FeatureNotFound exception with message:
> "Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?"

**Reproducing the error outside of doc2dash**
Trying to run a test file through `BeautifulSoup` produces the same error:
```python
from bs4 import BeautifulSoup
with open("test.html") as f:
    soup = BeautifulSoup(f, "lxml")
print(soup)
```

**Resolution**
Upgrading lxml to version 3.6.0 does the trick, doc2dash works fine.

**Comment by hynek** [comment]
This is confusing and seems more like some packaging/caching problem to me?  Can you import lxml?

**Comment by rlow0** [comment]
I think you're right that this is some kind of packaging or configuration issue. Importing lxml itself works, but trying to import any of its components (e.g. `import lxml.builder`) gives an error, saying that libxml isn't compatible with one of its shared libraries. Seems it's trying to load another version of libxml on the system, and not the version that comes with anaconda. Pointing it to the right library fixes the problem. lxml 2.6 was working without any trouble because its libraries were already loading anaconda's libxml properly. Thanks for your time!
