### ISSUE TITLE
Add option to ignore private methods/classes in pydoctor docs

### ISSUE THREAD

**Issue by Kapeli** [hynek/doc2dash#53]
Related to: https://github.com/twisted/pydoctor/issues/29#issuecomment-231683257.

The problem is that Dash (and doc2dash) currently treats private methods/classes the same with public ones. 

doc2dash should have an option that makes it completely ignore private methods/classes.

**Comment by hynek** [comment]
I believe this should be fixed after pydoctor moved to inter sphinx.
