### ISSUE TITLE
Supporting Sphinx user guides

### ISSUE THREAD

**Issue by jnothman** [hynek/doc2dash#57]
Sphinx is wont to output most of its documentation under the inventory key 'std:doc' which is currently handled with a `KeyError` and discarded by `doc2dash`.

Adding `std:doc` to `INV_TO_TYPE` (mapped to 'Guide') at least means these pages can be found in a search within Dash. But it leads to a few issues:
* The keys in `inv['std:doc']` are not the appropriate titles for the documentation pages, as assumed by `doc2dash`. Rather `inv['std:doc'][key][3]` contains the title.
* Pages containing API reference also appear in the guide, which may be inappropriate.
* Pages in the guide may otherwise be heterogeneous: I would consider typing some documentation as "Sample" rather than "Guide"; and "Tutorial" were such available in Dash.

So:
* is it worth making the intersphinx converter API more flexible to this case, or should projects be expected to adapt `doc2dash` to their needs (cf. concerns about use as a library #56, pinned requirements, etc. #54)?
* is the appropriate API a callback or perhaps regular expression-based rules?

**Comment by jnothman** [comment]
I think `BaseInterSphinxParser` should be designed with `inv_entry_to_dash(self, el, data_tuple) -> ParserEntry` as an overridable method; and `__main__` should have an option `--parser-class my.module.path.MyParser`.

**Comment by hynek** [comment]
At this point, would a release help you?

**Comment by jnothman** [comment]
Yes, thanks!

**Comment by hynek** [comment]
2.2.0 is on PyPI

**Comment by jnothman** [comment]
thanks! working towards release at scikit-learn means I'll not get to this
so soon.
