### ISSUE TITLE
Should the requirements be so specific?

### ISSUE THREAD

**Issue by WoLpH** [hynek/doc2dash#61]
Currently all of the requirements use a very specific version which means the project won't work with some of my other projects which require newer versions of Sphinx. Now I'm wondering, is there a reason for that or was this chosen by accident?

https://github.com/hynek/doc2dash/blob/master/setup.py#L13-L22

Should they be replaced with:
```
INSTALL_REQUIRES = [
    "Sphinx>=1.4.6",
    "attrs>=16.2.0",
    "beautifulsoup4>=4.5.1",
    "click>=6.6",
    "colorama>=0.3.7",
    "lxml>=3.6.4",
    "six>=1.10.0",
    "zope.interface>=4.3.2",
]
```

**Comment by hynek** [comment]
Doc2dash is an app and should be installed into a separate virtualenv.  Having dep updates break the installation would cause me many more issues than the monthly "why are the deps pinned" one.  I'm sympathetic for people who would like to embed it (cf #56) but I don't have time to work on it myself ATM.

**Comment by WoLpH** [comment]
That's fair. Thanks for the quick reply :)
