### ISSUE TITLE
Can't build ml-cheatsheet

### ISSUE THREAD

**Issue by esdotzed** [hynek/doc2dash#82]
https://github.com/bfortuner/ml-cheatsheet/tree/master/docs
I followed all the steps and finally after:
doc2dash ./_build/html/ -n ml-cheatsheet
I got:
Converting intersphinx docs from "html" to "./ml-cheatsheet.docset".
Parsing documentation...
Added 0 index entries.
Adding table of contents meta data...  [#######################################################################################################]  100%
Which basically gave me an empty file....

**Comment by hynek** [comment]
I don’t have the time to read all of it, but from a glance it seems like there’s only prose and no API information?

**Comment by esdotzed** [comment]
@hynek, I took another look, it actually generates correctly just without the indexing since it doesn’t have it! So no problem! One more question, there are latex formula in this doc which is not showing correctly in dash, any suggestions?

**Comment by hynek** [comment]
Unfortunately I have not.
