### ISSUE TITLE
Mypy sphynx documentation not supported ??

### ISSUE THREAD

**Issue by keufran** [hynek/doc2dash#94]
Hi,

I'm trying to generate a Dash docset for mypy, unfortunatly it doesn't work and I don't understand what I'm doing wrong.

I cloned the mypy repo
I installed doc2dash with pip
I go do mypy/docs
I type :
```
>doc2dash -n mypy .
``` 
End result is :
```
"/Users/XXXXX/dev/python/mypy/docs" does not contain a known documentation format.
```
I tried with enabling the -v option, with no more success.

Any help is welcomed 😃

**Comment by hynek** [comment]
I suspect that it doesn't offer API information (which makes sense, mypy doesn't offer a lot of programming APIs). Is there a file called `objects.inv` anywhere to be found?

**Comment by keufran** [comment]
No, this file doesn't exists. However it is created when building the doc (at least html).
I tried to build docset directly from html but, as stated in doc2dash's documentation, it didn't work.

**Comment by hynek** [comment]
How do you mean? The docs say:

> Building Sphinx documentation is usually easy: after installing the sphinx package, cd into their documentation directory (usually docs or doc) and enter make html.

https://doc2dash.readthedocs.io/en/stable/formats.html

**Comment by keufran** [comment]
Sorry, I'm not clear.

When I do this from mypy top-level directory, it doesn't work:
```
> cd  docs/
> make html
> doc2dash -n mypy -d doc2test/ .
```
Exits with:
```
/Users/xxxx/dev/python/mypy/docs/" does not contain a known documentation format
```
It almost works with:
```
> doc2dash -n mypy -d doc2test/ build/html
```
It exits with:
```
Converting intersphinx docs from "html" to "doc2dash/mypy.docset".
Parsing documentation...
Added 0 index entries.
```
Docset is generated but index is missing. Don't know if this is mypy or doc2dash fault.

**Comment by hynek** [comment]
It's mypy's fault. They don't generate any API-like index entries. I've looked into their objects.inv and all they give us is `['std:doc', 'std:label', 'std:cmdoption']`.  I guess some of them could be supported but overall their docs are not really made for an API browser…

**Comment by keufran** [comment]
Thank you Hynek to have taked time to look at this issue. 
And also: I wish you a very happy new year ! ;-)

**Comment by hynek** [comment]
Same for you!
