### ISSUE TITLE
Is it possible to build a docset from a reStructuredText file directly?

### ISSUE THREAD

**Issue by deinspanjer** [hynek/doc2dash#95]
I've used Dash for years, but have only dabbled in creating cheat sheets and such a couple of times.

Recently I've wanted to view docs for [httpie](https://httpie.org/doc) inside Dash, so I tried to do some research on how to do so.

It feels like it should be fairly straightforward since the doc page seems to be based on the [README.rst](https://github.com/jakubroztocil/httpie/blob/master/README.rst) file in the github repo, but even though I read that reStructuredText is some core component of Sphynx, it doesn't seem like doc2dash is expecting or understanding a single .rst file.

If you could provide any tips on how I might go about setting this up, it would be greatly appreciated.

**Comment by hynek** [comment]
A DocSet ist really just a bunch of HTML and index information. Sphinx has that information in a separate file which doc2dash reads. You can have a single file with no index of course, I believe there are simple examples at https://kapeli.com/docsets
